/*
 * er-http.h
 *
 */

#ifndef ER_HTTP_H_
#define ER_HTTP_H_
/*---------------------------------------------------------------------------*/
#include "contiki-net.h"
#include "sys/process.h"
#include "rest-engine.h"
/*---------------------------------------------------------------------------*/
/* Ideally a multiple of TCP_MSS */
#ifdef HTTPD_SIMPLE_CONF_MAIN_BUF_SIZE
#define HTTPD_SIMPLE_MAIN_BUF_SIZE HTTPD_SIMPLE_CONF_MAIN_BUF_SIZE
#else
#define HTTPD_SIMPLE_MAIN_BUF_SIZE UIP_TCP_MSS
#endif
/*---------------------------------------------------------------------------*/
#define HTTPD_PATHLEN  16
#define HTTPD_INBUF_LEN (HTTPD_PATHLEN + 10)

#define TMP_BUF_SIZE   (UIP_TCP_MSS + 1)
/*---------------------------------------------------------------------------*/
/* POST request handlers */
#define HTTPD_SIMPLE_POST_HANDLER_OK      1
#define HTTPD_SIMPLE_POST_HANDLER_UNKNOWN 0
#define HTTPD_SIMPLE_POST_HANDLER_ERROR   0xFFFFFFFF
/*---------------------------------------------------------------------------*/
//
#define MAX_URI_LEN	50

/**
 * \brief Datatype for a handler which can process incoming POST requests
 * \param key The configuration key to be updated
 * \param key_len The length of the key argument
 * \param val The new configuration value for key
 * \param val_len The length of the value argument
 *
 * \return 1: HTTPD_SIMPLE_POST_HANDLER_OK if the function can handle the
 * request, HTTPD_SIMPLE_POST_HANDLER_UNKNOWN if it does not know how to handle
 * it. HTTPD_SIMPLE_POST_HANDLER_ERROR if it does know how to handle it but
 * the request was malformed.
 */
typedef struct httpd_simple_post_handler {
  struct httpd_simple_post_handler *next;
  int (*handler)(char *key, int key_len, char *val, int val_len);
} httpd_simple_post_handler_t;

/* Declare a handler */
#define HTTPD_SIMPLE_POST_HANDLER(name, fp) \
  httpd_simple_post_handler_t name##_handler = { NULL, fp }


/*---------------------------------------------------------------------------*/
typedef struct http_response_t {
	uint8_t buf[HTTPD_SIMPLE_MAIN_BUF_SIZE];
	int blen;
	uint16_t content_type;
} http_response;

/*---------------------------------------------------------------------------*/
/* http request struct */
struct httpd_state {
  uint8_t buf[HTTPD_SIMPLE_MAIN_BUF_SIZE];
  char tmp_buf[TMP_BUF_SIZE];
  struct timer timer;
  struct psock sin, sout;

  const char **ptr;
  int content_length;

  size_t uri_len; 				/*!< uri-length >*/
  char uri[MAX_URI_LEN]; 		/* uri-name */

  int blen;
  int tmp_buf_len;
  int tmp_buf_copied;

  char inputbuf[HTTPD_INBUF_LEN];

  struct pt outputpt; //usada para gerar o output
  struct pt generate_pt; //usada para fazer headers

  char state;
  char request_type;
  char return_code;
  // response
  http_response response;
};
/*---------------------------------------------------------------------------*/

/**
 * \brief Register a handler for POST requests
 * \param h A pointer to the handler structure
 */
void httpd_simple_register_post_handler(httpd_simple_post_handler_t *h);

/** Register the RESTful service callback at implementation. */
void http_set_service_callback(service_callback_t callback);

/*---------------------------------------------------------------------------*/
/*
 * An event generated by the HTTPD when a new configuration request has been
 * received
 */
extern process_event_t httpd_simple_event_new_config;
/*---------------------------------------------------------------------------*/
PROCESS_NAME(httpd_process);
/*---------------------------------------------------------------------------*/



#endif /* ER_HTTP_H_ */
